services:
  linux:
    build: 
      context: .
      target: sfml-linux
    stdin_open: true
    tty: true
    volumes:
      - sfml-docker-template-vscode-extensions:/root/.vscode-server/extensions
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    network_mode: host
    
  macos:
    build: 
      context: .
      target: sfml-macos
    stdin_open: true
    tty: true
    volumes:
      - sfml-docker-template-vscode-extensions:/root/.vscode-server/extensions
      - .:/workspace

  windows:
    build: 
      context: .
      target: sfml-windows
    stdin_open: true
    tty: true
    volumes:
      - sfml-docker-template-vscode-extensions:/root/.vscode-server/extensions
      - .:/workspace

volumes:
  sfml-docker-template-vscode-extensions:
