services:
  # Setup
  setup-env-macos-arm64-debug:
    build: 
      context: .
      target: sfml-macos
    volumes:
      - .:/workspace
    command: ./scripts/setup_env_macos_arm64_debug.sh

  setup-env-windows-x86_64-debug:
    build: 
      context: .
      target: sfml-windows
    volumes:
      - .:/workspace
    command: ./scripts/setup-env-windows-x86_64-debug.sh

  # Interactive
  interactive-env-macos-arm64:
    build: 
      context: .
      target: sfml-macos
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace

  interactive-env-windows-x86_64:
    build: 
      context: .
      target: sfml-windows
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace

  # Compile
  compile-macos-arm64-debug:
    build:
      context: .
      target: sfml-macos
    volumes:
      - .:/workspace
    command: ./scripts/compile-macos-arm64-debug.sh

  compile-windows-x86_64-debug:
    build: 
      context: .
      target: sfml-windows
    volumes:
      - .:/workspace
    command: ./scripts/compile-windows-x86_64-debug.sh
