services:
  setup-env-macos-arm64-debug:
    build: 
      context: .
      target: sfml-macos
    volumes:
      - .:/workspace
    command: >
      sh -c "mkdir -p build/macos-arm64-debug/bin &&
             mkdir -p build/macos-arm64-debug/lib &&
             mkdir -p build/macos-arm64-debug/Frameworks &&
             cp -r /SFML/build/lib/*.dylib build/macos-arm64-debug/lib/ &&
             cp -r /SFML/extlibs/libs-osx/Frameworks/* build/macos-arm64-debug/Frameworks/"

  setup-env-windows-x86_64-debug:
    build: 
      context: .
      target: sfml-windows
    volumes:
      - .:/workspace
    command: >
      sh -c "mkdir -p build/windows-x86_64-debug &&
             mkdir -p build/windows-x86_64-debug &&
             cp -r /SFML/build/lib/*.dll build/windows-x86_64-debug/ &&
             cd /usr/lib/gcc/x86_64-w64-mingw32/10-win32
             cp libgcc_s_seh-1.dll libstdc++-6.dll /workspace/build/windows-x86_64-debug/"

  interactive-env:
    build: 
      context: .
      target: sfml-macos
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace

  compile-macos-arm64-debug:
    build:
      context: .
      target: sfml-macos
    volumes:
      - .:/workspace
    command: >
      sh -c "oa64-clang++ --std=c++17 -I/SFML/include -L/SFML/build/lib -lsfml-graphics-d -lsfml-window-d -lsfml-system-d -Wl,-rpath,'@executable_path/../lib' -o build/macos-arm64-debug/bin/sfml-test src/main.cpp"

  compile-windows-x86_64-debug:
    build: 
      context: .
      target: sfml-windows
    volumes:
      - .:/workspace
    command: >
      sh -c "x86_64-w64-mingw32-g++ -o build/windows-x86_64-debug/sfml-test.exe src/main.cpp -Wall --std=c++17 -I/SFML/include -L/SFML/build/lib -lsfml-graphics-d -lsfml-window-d -lsfml-system-d"
